/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверить доступность сервиса */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить каталог товаров */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать заказ */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить заказ */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оплатить заказ */
        post: operations["payOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить неоплаченный заказ и снять бронь */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принять уведомление об оплате */
        post: operations["receivePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/providers/{provider}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить код у поставщика */
        post: operations["issueFromProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить оплаченные, но не выданные заказы */
        get: operations["listStuckOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/promocodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Промокоды с текущим расходом лимита */
        get: operations["listPromocodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить цену товара */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поток изменений каталога */
        get: operations["catalogStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пополнить пул ключей */
        post: operations["restockKeys"];
        /** Убрать свободные ключи из пула */
        delete: operations["removeKeys"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{orderId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Повторить выдачу */
        post: operations["retryDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            sku: string;
            name: string;
            /** @enum {string} */
            type: "topup" | "key" | "subscription" | "giftcard";
            price: number;
            /** @description Цена до скидки */
            oldPrice?: number | null;
            currency: string;
            image?: string | null;
            /** @description Свободных единиц на складе */
            available?: number;
        };
        /** @enum {string} */
        OrderStatus: "created" | "paid" | "delivering" | "delivered" | "payment_failed" | "out_of_stock" | "delivery_failed";
        Order: {
            id: string;
            sku: string;
            /** @description Цена товара до скидки */
            amount: number;
            /** @description Размер скидки */
            discount: number;
            /** @description Сумма к оплате */
            total: number;
            currency: string;
            failureReason?: string | null;
            /** @description Машиночитаемая причина отказа */
            failureCode?: string | null;
            /** @description Цена товара в каталоге прямо сейчас */
            currentPrice: number;
            /** @description Заказ ждёт оплаты, и цена в каталоге разошлась с зафиксированной в нём */
            priceChanged: boolean;
            /**
             * Format: date-time
             * @description Момент снятия брони; null для любого заказа вне статуса created
             */
            reservationExpiresAt?: string | null;
            /** @description Остаток брони по часам сервера, чтобы не зависеть от часов клиента; null для любого заказа вне статуса created */
            expiresInMs?: number | null;
            promoCode?: string | null;
            status: components["schemas"]["OrderStatus"];
            /** @description Код активации товара */
            code?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateOrderRequest: {
            sku: string;
            promoCode?: string;
            idempotencyKey: string;
        };
        PayRequest: {
            /** @enum {string} */
            outcome: "success" | "fail";
        };
        PaymentWebhook: {
            event_id: string;
            order_id: string;
            /** @enum {string} */
            status: "paid" | "failed";
            amount: number;
            currency: string;
            /** Format: date-time */
            created_at: string;
        };
        IssueRequest: {
            request_id: string;
            sku: string;
            order_id: string;
        };
        IssueResponse: {
            /** @enum {string} */
            status: "ok";
            request_id: string;
            code: string;
        };
        IssueError: {
            /** @enum {string} */
            status: "error";
            reason: string;
        };
        ProductPatch: {
            price?: number;
            oldPrice?: number | null;
        };
        KeyRemovalResult: {
            sku: string;
            requested: number;
            removed: number;
            available: number;
        };
        KeyRemoval: {
            sku: string;
            count: number;
        };
        CheckoutConflict: {
            error: string;
            message: string;
            /** @description Другие предложения того же типа, доступные к покупке */
            alternatives?: {
                sku: string;
                name: string;
                price: number;
                currency: string;
                available: number;
            }[];
        };
        Error: {
            /** @enum {string} */
            error: "validation_error" | "not_found" | "conflict" | "promo_limit_reached" | "promo_not_found" | "out_of_stock" | "reservation_expired" | "promo_currency_mismatch" | "product_not_found" | "order_not_payable" | "order_not_cancellable" | "payment_in_progress" | "rate_limited" | "internal_error";
            message: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "error";
            /** @enum {string} */
            db: "up" | "down";
        };
        PaymentAccepted: {
            eventId: string;
        };
        WebhookAccepted: {
            accepted: boolean;
            deferred?: boolean;
        };
        RestockRequest: {
            sku: string;
            keys: string[];
        };
        RestockResult: {
            sku: string;
            added: number;
            available: number;
        };
        Promocode: {
            code: string;
            /** @enum {string} */
            type: "percent" | "amount";
            value: number;
            currency: string | null;
            maxUses: number;
            usedCount: number;
            remaining: number;
        };
        SkuParams: {
            sku: string;
        };
        OrderIdParams: {
            orderId: string;
        };
        ProviderParams: {
            /** @enum {string} */
            provider: "a" | "b";
        };
        AdminOrdersQuery: {
            /**
             * @description stuck — paid, delivering, out_of_stock, delivery_failed
             * @default stuck
             * @enum {string}
             */
            state: "stuck" | "all";
        };
    };
    responses: {
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Sku: string;
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис и база доступны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description База недоступна */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products: components["schemas"]["Product"][];
                    };
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Заказ уже существует */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Заказ создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Товар раскуплен либо промокод исчерпан */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutConflict"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    payOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            /** @description Вебхук отправлен */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Заказ нельзя оплатить в текущем статусе */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ отменён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Заказ уже нельзя отменить: оплачен, выдан или платёж в обработке */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    receivePaymentWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWebhook"];
            };
        };
        responses: {
            /** @description Событие принято */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Событие не принято */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issueFromProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "a" | "b";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequest"];
            };
        };
        responses: {
            /** @description Код выдан */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            /** @description Товара нет в наличии */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueError"];
                };
            };
            /** @description Поставщик недоступен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueError"];
                };
            };
        };
    };
    listStuckOrders: {
        parameters: {
            query?: {
                state?: "stuck" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список заказов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orders: components["schemas"]["Order"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listPromocodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список промокодов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        promocodes: components["schemas"]["Promocode"][];
                    };
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: components["parameters"]["Sku"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description Товар после изменения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    catalogStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Поток событий в формате text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    restockKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestockRequest"];
            };
        };
        responses: {
            /** @description Ключи добавлены */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestockResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    removeKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyRemoval"];
            };
        };
        responses: {
            /** @description Ключи убраны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyRemovalResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    retryDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ после попытки выдачи */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Заказ нельзя выдать в текущем статусе */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
