/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверить доступность сервиса */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить каталог товаров */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать заказ */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить заказ */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оплатить заказ */
        post: operations["payOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принять уведомление об оплате */
        post: operations["receivePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/providers/{provider}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить код у поставщика */
        post: operations["issueFromProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить оплаченные, но не выданные заказы */
        get: operations["listStuckOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пополнить пул ключей */
        post: operations["restockKeys"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{orderId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Повторить выдачу */
        post: operations["retryDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            sku: string;
            name: string;
            /** @enum {string} */
            type: "topup" | "key" | "subscription" | "giftcard";
            price: number;
            currency: string;
            image?: string | null;
        };
        /** @enum {string} */
        OrderStatus: "created" | "paid" | "delivering" | "delivered" | "payment_failed" | "out_of_stock" | "delivery_failed";
        Order: {
            id: string;
            sku: string;
            /** @description Цена товара до скидки */
            amount: number;
            /** @description Размер скидки */
            discount: number;
            /** @description Сумма к оплате */
            total: number;
            currency: string;
            failureReason?: string | null;
            promoCode?: string | null;
            status: components["schemas"]["OrderStatus"];
            /** @description Код активации товара */
            code?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateOrderRequest: {
            sku: string;
            promoCode?: string;
            idempotencyKey: string;
        };
        PayRequest: {
            /** @enum {string} */
            outcome: "success" | "fail";
        };
        PaymentWebhook: {
            event_id: string;
            order_id: string;
            /** @enum {string} */
            status: "paid" | "failed";
            amount: number;
            currency: string;
            /** Format: date-time */
            created_at: string;
        };
        IssueRequest: {
            request_id: string;
            sku: string;
            order_id: string;
        };
        IssueResponse: {
            /** @enum {string} */
            status: "ok";
            request_id: string;
            code: string;
        };
        IssueError: {
            /** @enum {string} */
            status: "error";
            reason: string;
        };
        Error: {
            /** @enum {string} */
            error: "validation_error" | "not_found" | "unauthorized" | "conflict" | "promo_limit_reached" | "promo_not_found" | "product_not_found" | "order_not_payable" | "rate_limited" | "not_implemented" | "internal_error";
            message: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "error";
            /** @enum {string} */
            db: "up" | "down";
        };
        PaymentAccepted: {
            eventId: string;
        };
        WebhookAccepted: {
            accepted: boolean;
            deferred?: boolean;
        };
        RestockRequest: {
            sku: string;
            keys: string[];
        };
        RestockResult: {
            sku: string;
            added: number;
            available: number;
        };
        OrderIdParams: {
            orderId: string;
        };
        ProviderParams: {
            /** @enum {string} */
            provider: "a" | "b";
        };
        AdminOrdersQuery: {
            /**
             * @description stuck — paid, delivering, out_of_stock, delivery_failed
             * @default stuck
             * @enum {string}
             */
            state: "stuck" | "all";
        };
    };
    responses: {
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нужен админский токен */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ещё не реализовано */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис и база доступны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description База недоступна */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products: components["schemas"]["Product"][];
                    };
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Заказ уже существует */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Заказ создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    payOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            /** @description Вебхук отправлен */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    receivePaymentWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWebhook"];
            };
        };
        responses: {
            /** @description Событие принято */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Событие не принято */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            501: components["responses"]["NotImplemented"];
        };
    };
    issueFromProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "a" | "b";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequest"];
            };
        };
        responses: {
            /** @description Код выдан */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            /** @description Товара нет в наличии */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueError"];
                };
            };
            /** @description Сбой поставщика */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueError"];
                };
            };
            501: components["responses"]["NotImplemented"];
        };
    };
    listStuckOrders: {
        parameters: {
            query?: {
                state?: "stuck" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список заказов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orders: components["schemas"]["Order"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            501: components["responses"]["NotImplemented"];
        };
    };
    restockKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestockRequest"];
            };
        };
        responses: {
            /** @description Ключи добавлены */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestockResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            501: components["responses"]["NotImplemented"];
        };
    };
    retryDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ после попытки выдачи */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
}
